services:
  para-aysah:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: para-aysah
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
